bind = "0.0.0.0:8001"
workers = 1  # Start with 1 worker for debugging
timeout = 120
accesslog = "-"  # Log to stdout
errorlog = "-"   # Log to stdout
capture_output = True
enable_stdio_inheritance = True
forwarded_allow_ips = '*'
loglevel = 'debug'
reload = True    # Enable auto-reload for development 